[CONNECT-442] Bootstrap app-connect-inbox
mirakl/app-connect-inbox pull request #1
Opened 2021-07-09 13:26 UTC by cchaudet

WIP

2021-07-20 08:54 UTC, cchaudet commented
test this please

2021-07-21 13:30 UTC, cchaudet commented
test this please

2021-07-21 15:38 UTC, VincentB-mirakl requested changes
C'est principalement des petites bricoles. Je t'avoue que je ne sais pas comment faire la review pour le fichier `ElasticsearchConfiguration.java` vu que je ne m'y connais pas trop dessus :man_shrugging: .

2021-07-21 15:38 UTC, VincentB-mirakl commented on Jenkinsfile
> +               def application = "connect-inbox-connector-mirakl"
```suggestion
               def application = "connect-inbox"
```

2021-07-21 15:38 UTC, VincentB-mirakl commented on README.md
> +|Main class|`com.mirakl.connect.inbox.connector.ConnectInboxConnectorApplication`|
`connector` Oops :smile:

2021-07-21 15:38 UTC, VincentB-mirakl commented on README.md
> +From the repo root, use the following command for jOOQ to create the source files inside `com.mirakl.connect.inbox.connector.jooq.generated` package (database must be running):
Pareil ici

2021-07-21 15:38 UTC, VincentB-mirakl commented on src/main/resources/application.yml
> +      - connect_inbox_connector_mirakl
```suggestion
      - connect_inbox
```

2021-07-21 15:38 UTC, VincentB-mirakl commented on pom.xml
> +                            <schemas>connect_inbox_connector_mirakl</schemas>
```suggestion
                            <schemas>connect_inbox</schemas>
```

2021-07-21 15:38 UTC, VincentB-mirakl commented on pom.xml
> +                                    <inputSchema>connect_inbox_connector_mirakl</inputSchema>
```suggestion
                                    <inputSchema>connect_inbox</inputSchema>
```

2021-07-21 15:38 UTC, VincentB-mirakl commented on pom.xml
> +                                    <packageName>com.mirakl.connect.inbox.connector.jooq.generated</packageName>
Pareil pour le nom du package :slightly_smiling_face:

2021-07-21 15:38 UTC, VincentB-mirakl commented on README.md
> +// TODO
Il reste un todo ici. Je suppose qu'on peut s'inspirer de app-connect-order et faire un replace sur le mot order :slightly_smiling_face: : .

2021-07-21 15:38 UTC, VincentB-mirakl commented on src/main/resources/application-development.yml
> +  port: 11011
C'est le même port que le connecteur, il faudrait en choisir un autre (je vois que la question est resté en suspend dans le ticket)

(Pareil pour le port du management)

2021-07-21 15:38 UTC, VincentB-mirakl commented on .gitignore
> +mcm-api-doc*.zip
Alors je crois qu'il y a eu des copier-coller en série de ce fichier parce que mcm-api-doc n'a de sens que pour le projet mcm :smile:

2021-07-21 15:38 UTC, VincentB-mirakl commented on src/main/resources/application-development.yml
> +  host: localhost
Pour lancer es en local, on utilise le docker du mirakl-compose ou un autre (j'ai vu un dossier tools/docker dans connect-order)?
On pourrait ajouter des infos dans le Readme là dessus, WDYT?

2021-07-21 15:38 UTC, VincentB-mirakl commented on src/main/java/com/mirakl/connect/inbox/utils/ParserUtils.java
> +        return Year.parse(year, DateTimeFormatter.ofPattern("u", Locale.getDefault()));
Comme vu ensemble, à toi de voir si tu préfère utiliser l'annot suppressForbidden de forbidden api ou pas.

2021-07-21 15:38 UTC, VincentB-mirakl commented on src/main/resources/application.yml
> +      - inbox
On peut enlever ce topic d'ici je pense. D'ailleurs pour les tests, on a parlé de se brancher au topic connect-store et de logguer l'info. Il faudrait rajouter ce consumer :slightly_smiling_face: .

2021-07-21 15:38 UTC, VincentB-mirakl commented on src/main/java/com/mirakl/connect/inbox/service/RefreshablePropertyResolver.java
> +public class RefreshablePropertyResolver {
Est-ce qu'on a vraiment besoin de ce service? :thinking:

2021-07-21 15:38 UTC, VincentB-mirakl commented on src/main/java/com/mirakl/connect/inbox/utils/ParserUtils.java
> +import org.springframework.core.io.ClassPathResource;
Je chipote un peu mais j'aime bien avoir un espace entre les imports et les noms des classes :sweat_smile:

2021-07-21 15:47 UTC, VincentB-mirakl commented on src/main/resources/application-development.yml
> +  host: localhost
Sorry, je n'avais pas vu que `Complete Readme.md` n'était pas coché dans la description de la PR :sweat_smile: .

2021-07-22 09:45 UTC, cchaudet commented on README.md
> +// TODO
Ah c'est smart :)

2021-07-22 09:47 UTC, cchaudet commented on src/main/resources/application-development.yml
> +  port: 11011
Ah oui, j'ai oublié de le mettre
J'ai choisit `11010` et `11110`, comme ça c'est le digit juste avant

2021-07-22 12:44 UTC, cchaudet commented on src/main/java/com/mirakl/connect/inbox/utils/ParserUtils.java
> +import org.springframework.core.io.ClassPathResource;
Non tu as raison ! Normalement mon code est formatté à chaque commit, mais comme c'est un nouveau projet je n'avais pas réactivé l'option. C'est chose faite !

2021-07-23 07:23 UTC, VincentB-mirakl commented on pom.xml
> +                            <schemas>connect_inbox_mirakl</schemas>
Je dirais `connect_inbox` plutôt :slightly_smiling_face: 

Pour le reste, LGTM :+1:

2021-07-23 07:44 UTC, VincentB-mirakl commented on src/main/java/com/mirakl/connect/inbox/ConnectInboxApplication.java
> +@Import({GracefulShutdownConfiguration.class, SentryMuteConfiguration.class})
Et j'avais zappé mais on peut importer `ContextRefreshConfiguration_NoLibMultitenant_SpringBoot_2_4.class` ici. :slightly_frowning_face: 

Cf: https://github.com/mirakl/lib-context-refresh

2021-07-23 14:00 UTC, VincentB-mirakl approved these changes

2021-07-23 14:19 UTC, agourd requested changes

2021-07-23 14:19 UTC, agourd commented on src/main/resources/application.yml
> +  topics:
Je pense qu'il faut qu'on mette "connect-store" dans les topics à filtrer non ?

2021-07-23 14:19 UTC, agourd commented on src/main/java/com/mirakl/connect/inbox/configuration/ElasticsearchConfiguration.java
> +    private String strategy;
Ça devrait pas être là ça non ?

2021-07-23 15:49 UTC, cchaudet commented on src/main/java/com/mirakl/connect/inbox/configuration/ElasticsearchConfiguration.java
> +    private String strategy;
Si j'ai bien compris, on se cale sur la stratégie de Flyway parce que ça pourrait donner des résultats incohérents. Effectivement il serait peut-être préférable de la renommer en `spring.migration-strategy` tout court mais pour l'instant j'ai préféré rester cohérent avec les autres projets

2021-07-23 15:56 UTC, agourd commented on src/main/java/com/mirakl/connect/inbox/configuration/ElasticsearchConfiguration.java
> +    private String strategy;
Mais la variable ne semble être inutilisée non ?

2021-07-26 05:53 UTC, rems commented on Jenkinsfile
> +        // Deploy on Continuous Delivery env only if it's a master build
nous avons ajouté un stage pour nous assurer qu'on ne merge pas dans master des dépendances "SNAPSHOTS"

CONNECT-543

exemple de PR : https://github.com/mirakl/app-connect-directory/pull/687/files

2021-07-26 08:06 UTC, agourd approved these changes

2021-07-26 12:19 UTC, cchaudet commented
!deploy connect3-test

2021-07-26 14:27 UTC, cchaudet commented
!deploy connect3-test

2021-07-26 15:26 UTC, cchaudet commented
!deploy connect3-test

2021-07-27 08:16 UTC, cchaudet commented
!deploy connect3-test

2021-07-27 14:40 UTC, cchaudet commented
!deploy connect3-test

2021-07-27 15:52 UTC, cchaudet commented
!deploy connect3-test

2021-07-28 15:11 UTC, agourd commented
!deploy connect3-test

2021-08-02 08:39 UTC, VincentB-mirakl commented
!deploy connect2-test

2021-08-02 12:18 UTC, merged